#! /bin/sh

#{{{Init Exec
sxhkd &
dunst &
exec ~/.config/polybar/launch_bs.sh &
picom &
mpd &
pulseaudio-equalizer enable &
nitrogen --restore &
#}}}

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           5
bspc config active_border_color \#1d2021
bspc config normal_border_color \#32302f

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#{{{bspc rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=floating
bspc rule -a St:cmus state=floating
bspc rule -a St:netctl state=floating
bspc rule -a St:htop state=floating
#}}}
