# Set theme
colorscheme gruvbox

# Set tab stop
set-option global tabstop 4
set-option global indentwidth 4

# Set scrolloff
set-option global scrolloff 1,3

# Set ncurses
set-option global ui_options ncurses_status_on_top=false

